version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8761:8761"

  apigatewayzuul:
    build:
      context: ./apigatewayzuul
    container_name: apigatewayzuul
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
    environment:
      - OAUTH_CLIENT_NAME=myappname123
      - OAUTH_CLIENT_SECRET=myappname123
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  usuario:
    build:
      context: ./usuario
    container_name: usuario
    volumes:
      - ~/.m2:/root/.m2
    depends_on:
      - config-server
      - eureka-server
      - apigatewayzuul
      - postgres-db
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_PASSWORD=provodromo_pass

  provodromo:
    build:
      context: ./provodromo
    container_name: provodromo
    volumes:
      - ~/.m2:/root/.m2
    depends_on:
      - config-server
      - eureka-server
      - apigatewayzuul
      - postgres-db
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_PASSWORD=provodromo_pass

  oauth:
    build:
      context: ./oauth
    container_name: oauth
    volumes:
      - ~/.m2:/root/.m2
    depends_on:
      - config-server
      - eureka-server
      - apigatewayzuul
    environment:
      - OAUTH_CLIENT_NAME=myappname123
      - OAUTH_CLIENT_SECRET=myappname123
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  postgres-db:
    image: postgres
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_PASSWORD: "provodromo_pass"