version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8761:8761"

  apigatewayzuul:
    build:
      context: ./apigatewayzuul
    container_name: apigatewayzuul
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
  
  worker:
    build:
      context: ./worker
    container_name: worker
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      - config-server

  usuario:
    build:
      context: ./usuario
    container_name: usuario
    volumes:
      - ~/.m2:/root/.m2
    depends_on:
      - config-server
      - eureka-server
      - apigatewayzuul
  
  oauth:
    build:
      context: ./oauth
    container_name: oauth
    volumes:
      - ~/.m2:/root/.m2
    depends_on:
      - config-server
      - eureka-server
      - apigatewayzuul
