version: '1.1'

services:
  sampleproject:
    image: provodromo-front
    build:
      context: ./provodromo-front
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000